version: "3.8"

services:

  yarrinspector:
    image: yarrinspector
    container_name: yarrinspector
    build: .
    restart: unless-stopped
    volumes:
      - ./app.py:/app/app.py
      - .streamlit:/app/.streamlit
    labels:
      - traefik.enable=true
      - traefik.http.routers.yarrinspector.rule=Host(`${HOST}`) && PathPrefix(`/yarr`) 
      - traefik.http.routers.yarrinspector.entrypoints=websecure
      - traefik.http.routers.yarrinspector.tls.certresolver=le
      - traefik.http.services.yarrinspector.loadbalancer.server.port=8501
      - traefik.http.middlewares.stripyarr.stripprefix.prefixes=/yarr
      - traefik.http.middlewares.stripyarr.stripprefix.forceSlash=true
      - traefik.http.routers.yarrinspector.middlewares=stripyarr@docker,yarrauth@docker #, allowed-ips@docker
      - traefik.http.routers.yarrinspector.service=yarrinspector@docker
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
